### ISSUE TITLE
Go 1.18.1 cannot compile WPN due to errros

### ISSUE THREAD

**Issue by vochong** [theSuess/wpn#3]
Hello,

Could you please fix the code to make it work with the new Go version 1.18.1.

Here are the errors when building it:

./client.go:35:31: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
./main.go:25:3: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:30:3: cannot use cli.BoolFlag{…} (value of type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:45:10: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
./main.go:79:5: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:84:5: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:89:5: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:94:5: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:99:5: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:104:5: cannot use cli.StringFlag{…} (value of type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:104:5: too many errors

$ go version
go version go1.18.1 linux/amd64
